var nome = "Maycon Santana";
var idade = 35;
var idade2 = 10;
var frase = "Japão é o melhor país pra viver";
//alert("Bem vindo " + nome + " sua idade é " + idade + " anos");
//alert(idade + idade2);
console.log(nome);
console.log(idade + idade2);
console.log(frase.replace("Japão", "Brasil"));
console.log(frase.toLowerCase());